name: CI

on:
  push:
    branches:
      - "*"
    tags-ignore:
      - v*

jobs:
  dry-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Use Node.js v18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "pnpm"
          cache-dependency-path: "./pnpm-lock.yaml"

      - run: pnpm install

      - run: npm publish --dry-run
