name: Publish Package
permissions:
  id-token: write
  # contents: write
on:
  push:
    branches: [main]
jobs:
  publish-npm:
    # if: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Use Node.js v18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
          cache: pnpm
      
      - run: pnpm install --frozen-lockfile

      # 检查版本是否包含 'beta'
      - name: Check for beta version
        id: check_version
        run: |
          if grep -q "beta" package.json; then
            echo "IS_BETA=true" >> $GITHUB_ENV
          else
            echo "IS_BETA=false" >> $GITHUB_ENV
          fi

      - name: Publish to npm
        run: |
          if [ $IS_BETA = "true" ]; then
            npm publish --access public --tag beta
          else
            npm publish --access public
          fi
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          NPM_CONFIG_PROVENANCE: true
